name: Publish minutes

on:
  push:
    paths:
    - '**/irc.log'

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - id: file_changes
      uses: trilom/file-changes-action@v1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: detect_file
      id: detect_file
      run: |
        echo ${{ steps.file_changes.outputs.files_modified}}
        echo ${{ steps.file_changes.outputs.files_added }}
        arr=${{ steps.file_changes.outputs.files_added }}
        echo arr
        new_file=${arr[0]}
        echo $new_file
        date=${new_file:1:10}
        echo $date
        dir=dirname ${new_file}
        echo $date
        echo "##[set-output name=date;]${date}"
        echo "##[set-output name=dir;]${dir}"
        group=`cat $output/group.txt`
        echo "##[set-output name=group;]${group}"
      shell: bash
    - name: Setup custom environment variables
      run: git config --global push.default simple && git config --global user.email "w3c.ccg@gmail.com" && git config --global user.name "W3C CCG"
    - name: Generate html minutes
      id: generate_html_minutes
      run: |
        npm install
        bash ./generate-html.sh
        echo "##[set-output name=date;]${DATE}"
        echo "##[set-output name=dir;]${DIR}"
      env:
        CI: true
        DATE: ${{ steps.detect_file.outputs.date }}
        
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Add html minutes for telecon [ci skip]
        branch: gh-pages

      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send email
      uses: dawidd6/action-send-mail@v1.3.0
   
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: w3c.ccg
        password: ${{ secrets.email_password }}
        subject: ${{ format('[MINUTES] W3C {0} Call - {1} 12pm ET', steps.generate_html_minutes.outputs.group, steps.generate_html_minutes.outputs.date) }}
        body: ${{ format('file://{0}/email.log', steps.generate_html_minutes.outputs.dir) }}
        to: public-credentials@w3.org
        from: W3C CCG Chairs
          
    - name: Twitter Action
      uses: ethomson/send-tweet-action@v1
      with:
        status: ${{ format('{0} Minutes Available https://w3c-ccg.github.io/meetings/{1}', steps.generate_html_minutes.outputs.group, steps.generate_html_minutes.outputs.dir) }}
        consumer-key: ${{ secrets.twitter_api_key }}
        consumer-secret: ${{ secrets.twitter_api_secret }}
        access-token: ${{ secrets.twitter_access_token }}
        access-token-secret: ${{ secrets.twitter_access_token_secret }}
